version: "3.9"
services:
  app:
    build: .
    volumes:
      - .:/code
    env_file:
      - .env
    links:
      - redis
  redis:
    image: redis
    volumes:
      - redis-data:/data
    entrypoint: redis-server --appendonly yes
volumes:
  redis-data:
